#!/usr/bin/env python3
"""
SentinelEdge — TFLite Conversion & Firmware Header Generation
==============================================================
Converts the trained Keras model to a fully quantized TFLite model (int8).
Generates all C headers needed by the ESP32 firmware.

Quantization strategy:
  - Full integer quantization (all weights + activations → int8)
  - Input tensor : int8  (firmware quantizes features before inference)
  - Output tensor: int8  (firmware dequantizes probabilities after inference)
  - Calibration  : 200 representative samples from training data

CRITICAL — Quantization parameters extracted here are embedded in model_settings.h.
The firmware uses these EXACT values to quantize/dequantize tensors.
Any mismatch = silent wrong predictions.

Also embeds StandardScaler parameters (mean + scale per feature) in model_settings.h
so the ESP32 can normalize features before quantization.

Outputs:
  models/fault_model.tflite               — quantized binary
  firmware/src/model/fault_model.h        — C array (equivalent to xxd -i)
  firmware/src/model/model_settings.h     — quantization params + scaler params
  models/model_report.json               — complete report (metrics + ESP32 estimates)
"""

import numpy as np
import json, time
from pathlib import Path

import tensorflow as tf
from tensorflow import keras

# ── Paths ──────────────────────────────────────────────────────────────────────

ML_DIR       = Path(__file__).parent
MODELS_DIR   = ML_DIR / "models"
DATA_DIR     = ML_DIR / "data"
FIRMWARE_DIR = ML_DIR.parent / "firmware" / "src" / "model"

KERAS_PATH   = MODELS_DIR / "real_fault_classifier.keras"
TFLITE_PATH  = MODELS_DIR / "fault_model.tflite"
REPORT_PATH  = MODELS_DIR / "real_model_report.json"

CLASSES       = ["stationary", "movement", "rotation", "shake"]
NUM_CLASSES   = 4
FEATURE_COUNT = 42
WINDOW_SIZE   = 200
STEP_SIZE     = 100
SAMPLE_RATE   = 100

# ── Quantization ───────────────────────────────────────────────────────────────

def make_representative_dataset(X_calibration: np.ndarray, n_samples: int = 200):
    """
    Generator of float32 samples for TFLite quantization calibration.
    Samples must cover the full range of the feature distribution so the
    quantizer can set accurate scale/zero_point for each tensor.
    """
    rng     = np.random.RandomState(42)
    indices = rng.choice(len(X_calibration), size=n_samples, replace=False)
    samples = X_calibration[indices].astype(np.float32)

    def generator():
        for sample in samples:
            yield [sample.reshape(1, FEATURE_COUNT)]

    return generator


def convert_to_tflite(model: keras.Model, rep_dataset_fn) -> bytes:
    """Full int8 quantization — all ops, input, and output tensors."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations               = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset      = rep_dataset_fn
    converter.target_spec.supported_ops   = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type        = tf.int8
    converter.inference_output_type       = tf.int8
    return converter.convert()


def extract_quant_params(tflite_path: str) -> dict:
    """
    Extract input/output quantization parameters from converted model.
    These are the authoritative scale/zero_point values the firmware must use.
    """
    interp = tf.lite.Interpreter(model_path=str(tflite_path))
    interp.allocate_tensors()

    inp = interp.get_input_details()[0]
    out = interp.get_output_details()[0]

    assert inp['dtype'] == np.int8, f"Input dtype is {inp['dtype']}, expected int8"
    assert out['dtype'] == np.int8, f"Output dtype is {out['dtype']}, expected int8"

    in_scale, in_zp   = inp['quantization']
    out_scale, out_zp = out['quantization']

    return {
        'input_shape':       list(inp['shape']),
        'output_shape':      list(out['shape']),
        'input_dtype':       'int8',
        'output_dtype':      'int8',
        'input_scale':       float(in_scale),
        'input_zero_point':  int(in_zp),
        'output_scale':      float(out_scale),
        'output_zero_point': int(out_zp),
    }

# ── C Header Generation ────────────────────────────────────────────────────────

def generate_fault_model_h(data: bytes) -> str:
    """
    Convert TFLite binary to C header (equivalent to: xxd -i fault_model.tflite).
    Uses alignas(16) for optimal DMA alignment on ESP32.
    """
    rows = []
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        rows.append("  " + ", ".join(f"0x{b:02x}" for b in chunk))
    array_body = ",\n".join(rows)

    return f"""\
// SentinelEdge — fault_model.h
// Auto-generated by ml/09_convert_real_model.py  —  DO NOT EDIT MANUALLY
//
// TFLite fault classifier model embedded as a C byte array.
// Source: models/fault_model.tflite  ({len(data):,} bytes, {len(data)/1024:.2f} KB)
// Load with: tflite::GetModel(fault_model_data)

#ifndef FAULT_MODEL_H
#define FAULT_MODEL_H

#include <stdint.h>

// Aligned for efficient ESP32 flash access (DRAM copy not needed with PROGMEM)
alignas(16) const uint8_t fault_model_data[] = {{
{array_body}
}};

const unsigned int fault_model_data_len = {len(data)}u;

#endif  // FAULT_MODEL_H
"""


def format_float_array(values: list, name: str, comment: str = "") -> str:
    """Format a float array as a C constexpr declaration."""
    entries = []
    for i in range(0, len(values), 4):
        chunk = values[i:i + 4]
        entries.append("  " + ", ".join(f"{v:.8f}f" for v in chunk))
    body = ",\n".join(entries)
    comment_line = f"  // {comment}\n" if comment else ""
    return f"constexpr float {name}[{len(values)}] = {{\n{comment_line}{body}\n}};"


def generate_model_settings_h(quant: dict, model_size: int, scaler: dict) -> str:
    """
    Generate model_settings.h with all firmware constants.

    Includes:
    - Tensor arena size
    - Input/output shapes
    - Input/output quantization scale + zero_point
    - StandardScaler mean + scale arrays (42 values each)
    - Fault class labels and inference threshold
    """
    tensor_arena_bytes = 12 * 1024  # 12KB — conservative for Dense(42→32→16→4)

    # Estimate ESP32 SRAM consumption
    # Tensor arena  : 12KB
    # 6 axis buffers: 6 × 200 × 4 bytes = 4,800 bytes
    # Feature array : 42 × 4 bytes = 168 bytes
    # TFLite objects: ~2KB overhead (resolver, interpreter)
    est_sram = tensor_arena_bytes + 6*WINDOW_SIZE*4 + FEATURE_COUNT*4 + 2048

    scaler_mean_arr  = format_float_array(
        scaler['mean'], "kScalerMean",
        "StandardScaler mean per feature — subtract before dividing by scale"
    )
    scaler_scale_arr = format_float_array(
        scaler['scale'], "kScalerScale",
        "StandardScaler scale (std dev) per feature — divide after subtracting mean"
    )

    return f"""\
// SentinelEdge — model_settings.h
// Auto-generated by ml/09_convert_real_model.py  —  DO NOT EDIT MANUALLY
//
// All constants required by the ESP32 TFLite Micro inference pipeline.
// Generated from the actual trained + quantized model — values are exact.

#ifndef MODEL_SETTINGS_H
#define MODEL_SETTINGS_H

#include <cstdint>

// ─── Tensor Arena ────────────────────────────────────────────────────────────
// Static memory pool allocated on the stack for TFLite Micro.
// Too small → AllocateTensors() fails at startup (fatal).
// Too large → wastes SRAM. Tune after measuring actual usage.
constexpr int kTensorArenaSize = {tensor_arena_bytes};  // {tensor_arena_bytes // 1024}KB

// ─── Shapes ───────────────────────────────────────────────────────────────────
constexpr int kFeatureCount  = {quant['input_shape'][-1]};    // 42 features per window
constexpr int kNumClasses    = {quant['output_shape'][-1]};     // 4 fault classes
constexpr int kWindowSize    = {WINDOW_SIZE};   // samples per inference window (200)
constexpr int kStepSize      = {STEP_SIZE};    // sliding window step (100)
constexpr int kSampleRateHz  = {SAMPLE_RATE};    // MPU6050 sampling rate (Hz)

// ─── Input Quantization ───────────────────────────────────────────────────────
// Converts NORMALIZED float features → int8 for model input.
// Formula: q = clamp(round(f / kInputScale) + kInputZeroPoint, -128, 127)
// NOTE: 'f' here is the NORMALIZED feature (after subtracting mean, dividing by scale).
constexpr float   kInputScale     = {quant['input_scale']:.8f}f;
constexpr int32_t kInputZeroPoint = {quant['input_zero_point']};

// ─── Output Quantization ──────────────────────────────────────────────────────
// Converts int8 model output → float probability.
// Formula: prob = (q - kOutputZeroPoint) * kOutputScale
// For class selection: argmax on raw int8 values is equivalent (no dequant needed).
// For confidence: dequantize the winning class probability.
constexpr float   kOutputScale     = {quant['output_scale']:.8f}f;
constexpr int32_t kOutputZeroPoint = {quant['output_zero_point']};

// ─── Inference Threshold ─────────────────────────────────────────────────────
// Only publish MQTT anomaly events if confidence exceeds this threshold.
// Confidence = (output_int8[best_class] - kOutputZeroPoint) * kOutputScale
constexpr float kConfidenceThreshold = 0.75f;

// ─── Fault Class Labels ───────────────────────────────────────────────────────
constexpr int kClassStationary = 0;
constexpr int kClassMovement   = 1;
constexpr int kClassRotation   = 2;
constexpr int kClassShake      = 3;

constexpr const char* kFaultLabels[] = {{
  "stationary",   // 0
  "movement",     // 1
  "rotation",     // 2
  "shake"         // 3
}};

// ─── Model Size ───────────────────────────────────────────────────────────────
constexpr unsigned int kModelSizeBytes = {model_size}u;  // {model_size/1024:.2f} KB in flash

// ─── Estimated ESP32 SRAM Usage ──────────────────────────────────────────────
// Tensor arena  : {tensor_arena_bytes // 1024}KB
// Axis buffers  : {6*WINDOW_SIZE*4} bytes (6 axes × {WINDOW_SIZE} samples × 4 bytes)
// Feature array : {FEATURE_COUNT*4} bytes (42 features × 4 bytes)
// TFLite objects: ~2KB overhead
// Total estimate: ~{est_sram // 1024}KB of {520}KB available SRAM
constexpr int kEstimatedSramBytes = {est_sram};

// ─── StandardScaler Parameters ───────────────────────────────────────────────
// Applied to raw features BEFORE quantization.
// Normalization: f_norm = (f_raw - mean) / scale
// These values were computed by sklearn.preprocessing.StandardScaler
// on the training set (n={scaler.get('n_samples_fit', 'N/A')}).
// Order matches feature_utils.py: ax_mean, ax_std, ..., gz_spectral_energy

{scaler_mean_arr}

{scaler_scale_arr}

#endif  // MODEL_SETTINGS_H
"""


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    FIRMWARE_DIR.mkdir(parents=True, exist_ok=True)

    print("=" * 62)
    print("SentinelEdge — TFLite Conversion")
    print("=" * 62)

    # ── Load model ────────────────────────────────────────────────────────
    if not KERAS_PATH.exists():
        raise FileNotFoundError(f"Keras model not found: {KERAS_PATH}\nRun 03_train_model.py first.")

    print(f"\nLoading Keras model: {KERAS_PATH}")
    model = keras.models.load_model(KERAS_PATH)
    model.summary()

    # ── Load scaler + features ────────────────────────────────────────────
    with open(MODELS_DIR / 'real_scaler_params.json') as f:
        scaler_params = json.load(f)

    data = np.load(DATA_DIR / 'real_features.npz', allow_pickle=True)
    X_raw = data['X'].astype(np.float32)
    mean_v  = np.array(scaler_params['mean'],  dtype=np.float32)
    scale_v = np.array(scaler_params['scale'], dtype=np.float32)
    X_scaled = (X_raw - mean_v) / scale_v

    # ── Convert ───────────────────────────────────────────────────────────
    print(f"\nConverting to TFLite int8 (calibrating with 200 samples)...")
    rep_fn = make_representative_dataset(X_scaled, n_samples=200)
    t0 = time.perf_counter()
    tflite_bytes = convert_to_tflite(model, rep_fn)
    conv_time = time.perf_counter() - t0

    TFLITE_PATH.write_bytes(tflite_bytes)
    model_size = len(tflite_bytes)

    print(f"  Conversion time : {conv_time:.2f}s")
    print(f"  Model size      : {model_size:,} bytes  ({model_size/1024:.2f} KB)")
    assert model_size < 100 * 1024, f"Model {model_size/1024:.1f}KB exceeds 100KB target!"
    print(f"  OK Size target met (< 100KB)")

    # ── Extract quantization parameters ───────────────────────────────────
    print(f"\nExtracting quantization parameters...")
    quant = extract_quant_params(TFLITE_PATH)
    print(f"  Input  shape       : {quant['input_shape']}")
    print(f"  Output shape       : {quant['output_shape']}")
    print(f"  Input  scale       : {quant['input_scale']:.8f}")
    print(f"  Input  zero_point  : {quant['input_zero_point']}")
    print(f"  Output scale       : {quant['output_scale']:.8f}")
    print(f"  Output zero_point  : {quant['output_zero_point']}")

    # ── Generate C headers ────────────────────────────────────────────────
    print(f"\nGenerating firmware headers -> {FIRMWARE_DIR}/")

    fault_model_h = generate_fault_model_h(tflite_bytes)
    (FIRMWARE_DIR / "fault_model.h").write_text(fault_model_h, encoding='utf-8')
    print(f"  OK fault_model.h        ({model_size:,} bytes as C array)")

    settings_h = generate_model_settings_h(quant, model_size, scaler_params)
    (FIRMWARE_DIR / "model_settings.h").write_text(settings_h, encoding='utf-8')
    print(f"  OK model_settings.h     (quant params + scaler: {FEATURE_COUNT}×2 floats)")

    # ── Load Keras metrics ─────────────────────────────────────────────────
    keras_metrics = {}
    km_path = MODELS_DIR / 'keras_metrics.json'
    if km_path.exists():
        with open(km_path) as f:
            keras_metrics = json.load(f)

    # ── Build model_report.json ───────────────────────────────────────────
    tensor_arena = 12 * 1024
    est_sram = tensor_arena + 6 * WINDOW_SIZE * 4 + FEATURE_COUNT * 4 + 2048

    report = {
        "generated_by":    "ml/09_convert_real_model.py",
        "model_file":      "fault_model.tflite",
        "model_size_bytes": model_size,
        "model_size_kb":    round(model_size / 1024, 2),
        "input_shape":      quant['input_shape'],
        "output_shape":     quant['output_shape'],
        "input_dtype":      quant['input_dtype'],
        "output_dtype":     quant['output_dtype'],
        "input_scale":      quant['input_scale'],
        "input_zero_point": quant['input_zero_point'],
        "output_scale":     quant['output_scale'],
        "output_zero_point": quant['output_zero_point'],
        "classes":              CLASSES,
        "feature_count":        FEATURE_COUNT,
        "window_size":          WINDOW_SIZE,
        "step_size":            STEP_SIZE,
        "sample_rate_hz":       SAMPLE_RATE,
        "confidence_threshold": 0.75,
        "architecture": {
            "layers": [
                {"name": "input",   "units": FEATURE_COUNT, "activation": "none"},
                {"name": "dense_1", "units": 32,            "activation": "relu"},
                {"name": "dense_2", "units": 16,            "activation": "relu"},
                {"name": "output",  "units": NUM_CLASSES,   "activation": "softmax"},
            ],
            "total_params": (FEATURE_COUNT*32+32) + (32*16+16) + (16*NUM_CLASSES+NUM_CLASSES),
        },
        "metrics": {
            "keras_accuracy":      keras_metrics.get('accuracy'),
            "keras_fpr":           keras_metrics.get('false_positive_rate'),
            "precision_per_class": keras_metrics.get('precision_per_class'),
            "recall_per_class":    keras_metrics.get('recall_per_class'),
            "f1_per_class":        keras_metrics.get('f1_per_class'),
            # Filled by 05_validate_tflite.py:
            "tflite_accuracy":     None,
            "accuracy_drop":       None,
            "tflite_fpr":          None,
            "tflite_latency_ms_python": None,
        },
        "estimated_esp32": {
            "tensor_arena_bytes":        tensor_arena,
            "tensor_arena_kb":           tensor_arena // 1024,
            "axis_buffers_bytes":        6 * WINDOW_SIZE * 4,
            "feature_array_bytes":       FEATURE_COUNT * 4,
            "estimated_total_sram_bytes": est_sram,
            "estimated_total_sram_kb":   round(est_sram / 1024, 1),
            "flash_model_bytes":         model_size,
            "flash_model_kb":            round(model_size / 1024, 2),
            "total_sram_available_kb":   520,
            "sram_usage_pct":            round(est_sram / (520*1024) * 100, 1),
        },
    }

    class NumpyEncoder(json.JSONEncoder):
        def default(self, obj):
            if isinstance(obj, (np.integer, int)): return int(obj)
            if isinstance(obj, (np.floating, float)): return float(obj)
            if isinstance(obj, np.ndarray): return obj.tolist()
            return super(NumpyEncoder, self).default(obj)

    with open(REPORT_PATH, 'w') as f:
        json.dump(report, f, indent=2, cls=NumpyEncoder)
    print(f"\nOK Model report (partial): {REPORT_PATH}")

    print(f"\n{'='*62}")
    print("CONVERSION SUMMARY")
    print(f"{'='*62}")
    print(f"  Model size       : {model_size/1024:.2f} KB  (target < 100 KB)")
    print(f"  Keras accuracy   : {keras_metrics.get('accuracy', 'N/A')}")
    print(f"  Input scale      : {quant['input_scale']:.8f}")
    print(f"  Input zero_point : {quant['input_zero_point']}")
    print(f"  Est. SRAM usage  : {est_sram/1024:.1f} KB / 520 KB  "
          f"({est_sram/(520*1024)*100:.1f}%)")
    print(f"\nNext -> Run 10_validate_real_model.py to verify accuracy parity.")


if __name__ == "__main__":
    main()
