// SentinelEdge — features.h
// ==========================
// Circular buffer management and feature extraction.
//
// CANONICAL ALGORITHM: Must match ml/feature_utils.py exactly.
// Any deviation causes model input distribution drift → silent wrong predictions.
//
// Features (7 per axis × 6 axes = 42 total):
//   [0] mean              — sum(x) / N
//   [1] std               — sqrt(sum((x-mean)²) / N)  [population, ddof=0]
//   [2] variance          — sum((x-mean)²) / N         [population, ddof=0]
//   [3] rms               — sqrt(sum(x²) / N)
//   [4] peak_to_peak      — max(x) - min(x)
//   [5] dominant_freq_bin — argmax(|FFT|[1..N/2]), 1-indexed, skips DC
//   [6] spectral_energy   — sum(|FFT|[1..N/2]²), unnormalized, no windowing
//
// Axis order: ax, ay, az, gx, gy, gz
// Feature order: all 7 for ax, then ay, az, gx, gy, gz

#ifndef FEATURES_H
#define FEATURES_H

#include <Arduino.h>
#include "model/model_settings.h"

// ── Constants ──────────────────────────────────────────────────────────────────
#define NUM_AXES       6
#define FEATURES_PER_AXIS  7

// ── Circular Buffer ────────────────────────────────────────────────────────────
// One buffer per axis. Filled at 100Hz, feature extraction runs every STEP_SIZE.
// Memory: 6 × 200 × 4 bytes = 4,800 bytes (fits in SRAM easily)
extern float axBuf[kWindowSize];
extern float ayBuf[kWindowSize];
extern float azBuf[kWindowSize];
extern float gxBuf[kWindowSize];
extern float gyBuf[kWindowSize];
extern float gzBuf[kWindowSize];

// Current write index in the circular buffer (0..kWindowSize-1)
extern int   bufferIdx;
// Total samples pushed (used to detect when first full window is available)
extern int   totalSamples;

// ── Feature Array ──────────────────────────────────────────────────────────────
// Output of extractFeatures(). Normalized float values ready for quantization.
extern float features[kFeatureCount];

// ── Timing Metrics ────────────────────────────────────────────────────────────
// Set by extractFeatures(). Used for benchmarking report.
extern unsigned long featureExtractionUs;  // microseconds

// ── Function Declarations ──────────────────────────────────────────────────────

/**
 * Initialize circular buffers to zero.
 */
void initBuffers();

/**
 * Push one sample into all 6 axis circular buffers.
 * Call at 100Hz from the main loop.
 *
 * @param ax  X-axis acceleration (m/s²)
 * @param ay  Y-axis acceleration (m/s²)
 * @param az  Z-axis acceleration (m/s²)
 * @param gx  X-axis angular velocity (deg/s)
 * @param gy  Y-axis angular velocity (deg/s)
 * @param gz  Z-axis angular velocity (deg/s)
 */
void pushSample(float ax, float ay, float az, float gx, float gy, float gz);

/**
 * Check whether a full window is available for feature extraction.
 * Returns true after kWindowSize samples have been collected AND
 * every kStepSize samples thereafter.
 */
bool windowReady();

/**
 * Extract 42 features from the current circular buffer contents.
 * Writes results into the global `features[]` array (raw, un-normalized).
 *
 * This function is the C++ mirror of feature_utils.py::extract_features_window().
 * Uses arduinoFFT with FFT_WIN_TYP_RECTANGLE (no windowing) to match numpy rfft.
 *
 * After this call, `features[]` holds raw (un-normalized) float values.
 * Call normalizeFeatures() before quantization.
 *
 * Also sets featureExtractionUs with wall-clock time taken.
 */
void extractFeatures();

/**
 * Apply StandardScaler normalization to features[].
 * f_norm = (f_raw - kScalerMean[i]) / kScalerScale[i]
 *
 * Must be called after extractFeatures() and before quantizeFeatures().
 * Scale parameters are embedded in model_settings.h (generated by Phase 1).
 */
void normalizeFeatures();

/**
 * Quantize normalized features to int8 for TFLite input tensor.
 * q = clamp(round(f / kInputScale) + kInputZeroPoint, -128, 127)
 *
 * Must be called after normalizeFeatures().
 *
 * @param inputTensor  Pointer to TFLite input tensor data (int8_t array)
 */
void quantizeFeatures(int8_t* inputTensor);

#ifdef DRIFT_CHECK_ENABLED
/**
 * Generate deterministic drift-check windows and print 42 features per class.
 * Call when serial input 'd' is received.
 * Output format matches 06_feature_drift_validation.py expectations:
 *   DRIFT_CLASS:0
 *   0.98100001
 *   ... (42 lines)
 *   DRIFT_CLASS:1
 *   ...
 */
void printDriftCheckFeatures();
#endif  // DRIFT_CHECK_ENABLED

#endif  // FEATURES_H
