// SentinelEdge — model_settings.h
// Auto-generated by ml/09_convert_real_model.py  —  DO NOT EDIT MANUALLY
//
// All constants required by the ESP32 TFLite Micro inference pipeline.
// Generated from the actual trained + quantized model — values are exact.

#ifndef MODEL_SETTINGS_H
#define MODEL_SETTINGS_H

#include <cstdint>

// ─── Tensor Arena ────────────────────────────────────────────────────────────
// Static memory pool allocated on the stack for TFLite Micro.
// Too small → AllocateTensors() fails at startup (fatal).
// Too large → wastes SRAM. Tune after measuring actual usage.
constexpr int kTensorArenaSize = 12288;  // 12KB

// ─── Shapes ───────────────────────────────────────────────────────────────────
constexpr int kFeatureCount  = 42;    // 42 features per window
constexpr int kNumClasses    = 4;     // 4 fault classes
constexpr int kWindowSize    = 200;   // samples per inference window (200)
constexpr int kStepSize      = 100;    // sliding window step (100)
constexpr int kSampleRateHz  = 100;    // MPU6050 sampling rate (Hz)

// ─── Input Quantization ───────────────────────────────────────────────────────
// Converts NORMALIZED float features → int8 for model input.
// Formula: q = clamp(round(f / kInputScale) + kInputZeroPoint, -128, 127)
// NOTE: 'f' here is the NORMALIZED feature (after subtracting mean, dividing by scale).
constexpr float   kInputScale     = 0.05758044f;
constexpr int32_t kInputZeroPoint = -43;

// ─── Output Quantization ──────────────────────────────────────────────────────
// Converts int8 model output → float probability.
// Formula: prob = (q - kOutputZeroPoint) * kOutputScale
// For class selection: argmax on raw int8 values is equivalent (no dequant needed).
// For confidence: dequantize the winning class probability.
constexpr float   kOutputScale     = 0.00390625f;
constexpr int32_t kOutputZeroPoint = -128;

// ─── Inference Threshold ─────────────────────────────────────────────────────
// Only publish MQTT anomaly events if confidence exceeds this threshold.
// Confidence = (output_int8[best_class] - kOutputZeroPoint) * kOutputScale
constexpr float kConfidenceThreshold = 0.75f;

// ─── Fault Class Labels ───────────────────────────────────────────────────────
constexpr int kClassStationary = 0;
constexpr int kClassMovement   = 1;
constexpr int kClassRotation   = 2;
constexpr int kClassShake      = 3;

constexpr const char* kFaultLabels[] = {
  "stationary",   // 0
  "movement",     // 1
  "rotation",     // 2
  "shake"         // 3
};

// ─── Model Size ───────────────────────────────────────────────────────────────
constexpr unsigned int kModelSizeBytes = 1808u;  // 1.77 KB in flash

// ─── Estimated ESP32 SRAM Usage ──────────────────────────────────────────────
// Tensor arena  : 12KB
// Axis buffers  : 4800 bytes (6 axes × 200 samples × 4 bytes)
// Feature array : 168 bytes (42 features × 4 bytes)
// TFLite objects: ~2KB overhead
// Total estimate: ~18KB of 520KB available SRAM
constexpr int kEstimatedSramBytes = 19304;

// ─── StandardScaler Parameters ───────────────────────────────────────────────
// Applied to raw features BEFORE quantization.
// Normalization: f_norm = (f_raw - mean) / scale
// These values were computed by sklearn.preprocessing.StandardScaler
// on the training set (n=N/A).
// Order matches feature_utils.py: ax_mean, ax_std, ..., gz_spectral_energy

constexpr float kScalerMean[42] = {
  // StandardScaler mean per feature — subtract before dividing by scale
  7.43672180f, 2.50560825f, 13.30692612f, 9.21589802f,
  10.19602322f, 19.55454545f, 266152.96797109f, 0.03120803f,
  2.64096768f, 20.38221209f, 3.03888529f, 9.86237899f,
  18.95454545f, 407654.14606925f, -2.29222016f, 2.80313151f,
  22.27505356f, 4.31246437f, 10.56241946f, 18.59696970f,
  445512.71459508f, -0.73945010f, 51.70903790f, 7740.03004106f,
  55.47934533f, 159.68785706f, 17.36969697f, 154802979.68430936f,
  0.38217257f, 29.55331155f, 1927.82439372f, 37.03084418f,
  130.80663962f, 22.17272727f, 38557632.71166270f, -1.44556129f,
  34.59235430f, 2584.72986749f, 40.14628538f, 142.71084922f,
  19.07878788f, 51695689.16486555f
};

constexpr float kScalerScale[42] = {
  // StandardScaler scale (std dev) per feature — divide after subtracting mean
  4.21641786f, 2.65119849f, 19.68193632f, 1.20712901f,
  9.49880044f, 26.64704874f, 393656.26619879f, 1.60952547f,
  3.66162557f, 47.67552110f, 3.70660686f, 11.78286090f,
  25.62871958f, 953533.91453786f, 1.85812599f, 3.79703928f,
  47.19084813f, 3.51917747f, 12.26931708f, 27.50787198f,
  943830.16820373f, 17.13232379f, 71.17728177f, 14900.28831129f,
  70.39982662f, 182.56948249f, 26.19628108f, 298010069.50287855f,
  36.81260868f, 32.47192896f, 4015.74177075f, 43.72476628f,
  124.44807041f, 28.32790436f, 80317539.28243908f, 31.14285357f,
  37.25719919f, 4136.80941900f, 44.10184366f, 143.62057973f,
  27.70876415f, 82738256.55114542f
};

#endif  // MODEL_SETTINGS_H
